{% set version = "2.6.1" %}
{% set build_number = 1 %}
{% set is_noop = is_noop | default("false") %}

package:
  name: legacy-cgi
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/legacy-cgi/legacy_cgi-{{ version }}.tar.gz
  sha256: f2ada99c747c3d72a473a6aaff6259a61f226b06fe9f3106e495ab83fd8f7a42

build:
  noarch: python
{% if is_noop == "true" %}
  number: {{ build_number * 2 }}
{% else %}
  number: {{ (build_number * 2) + 1 }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
{% endif %}

requirements:
{% if is_noop == "true" %}
  host:
    - python <3.10
  run:
    - python <3.10
{% else %}
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.10.0
  run:
    - python >=3.10.0
{% endif %}

test:
  imports:
    - cgi
    - cgitb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jackrosenthal/legacy-cgi
  summary: Fork of the standard library cgi and cgitb modules, being deprecated in PEP-594
  license: EPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
