schema_version: 1

context:
  version: 2.6.1
  number: 2
  effective_build_number: ${{ (number | int) * 2 + (0 if is_noop == "true" else 1) }}
  removed_in_python: "3.10"
  python_min: ${{ python_min if is_noop == "true" else removed_in_python }}

package:
  name: legacy-cgi
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/legacy-cgi/legacy_cgi-${{ version }}.tar.gz
  sha256: f2ada99c747c3d72a473a6aaff6259a61f226b06fe9f3106e495ab83fd8f7a42

build:
  number: ${{ effective_build_number }}
  noarch: python
  script:
    - if: is_noop == "true"
      then:
        - echo "this is a no-op package"
      else:
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - if: is_noop == "true"
      then:
        - python ${{ python_min }}.*
      else:
        - pip
        - poetry-core >=1.0.0
        - python ${{ python_min }}.*
  run:
    - if: is_noop == "true"
      then:
        - python >=${{ python_min }},<${{ removed_in_python }}
      else:
        - python >=${{ python_min }}

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports:
        - cgi
        - cgitb

about:
  homepage: https://github.com/jackrosenthal/legacy-cgi
  summary: Fork of the standard library cgi and cgitb modules, being deprecated in PEP-594
  license: EPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
