# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.6.3"
  number: 0
  removed_in_python: "3.10"
  # linter complains if any of this is done with if/then/else below
  effective_build_number: ${{ (number | int) * 2 + (1 if is_noop == "true" else 0) }}
  python_min: ${{ removed_in_python  if is_noop == "false" else  python_min }}
  python_max: ${{ ""                 if is_noop == "false" else  ",<" ~ removed_in_python }}

package:
  name: legacy-cgi
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/legacy-cgi/legacy_cgi-${{ version }}.tar.gz
  sha256: 4c119d6cb8e9d8b6ad7cc0ddad880552c62df4029622835d06dfd18f438a8154

build:
  number: ${{ effective_build_number }}
  noarch: python
  script:
    - ${{ (PYTHON ~ " " ~ RECIPE_DIR ~ "/patch_noop.py") if is_noop == "true" else "echo no patch needed" }}
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
    - tomli
    - tomli-w
  run:
    - python >=${{ python_min }}${{ python_max }}

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports:
        - cgi
        - cgitb

about:
  homepage: https://github.com/jackrosenthal/legacy-cgi
  summary: Fork of the standard library cgi and cgitb modules, being deprecated in PEP-594
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
