schema_version: 1

context:
  version: "2.6.2"
  number: 0
  effective_build_number: ${{ (number | int) * 2 + (0 if is_noop == "true" else 1) }}
  removed_in_python: "3.10"
  python_min: ${{ python_min if is_noop == "true" else removed_in_python }}
  python_max: ${{ ",<" ~ removed_in_python if is_noop == "true" else "" }}
  install_pip: -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  install_script: ${{ "-c 'import sys; print(\"no-op on\", sys.version)'" if is_noop == "true" else install_pip }}

package:
  name: legacy-cgi
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/legacy-cgi/legacy_cgi-${{ version }}.tar.gz
  sha256: 9952471ceb304043b104c22d00b4f333cac27a6abe446d8a528fc437cf13c85f

build:
  number: ${{ effective_build_number }}
  noarch: python
  script: ${{ PYTHON }} ${{ install_script }}

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}${{ python_max }}

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports:
        - cgi
        - cgitb

about:
  homepage: https://github.com/jackrosenthal/legacy-cgi
  summary: Fork of the standard library cgi and cgitb modules, being deprecated in PEP-594
  license: EPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
